import { useEffect, useState } from 'react';

import Loader from '../../components/Loader/Loader';
import Card from '../../components/Card/Card';
import FormField from '../../components/FormField/FormField';

import styles from './Home.module.scss';

function Home() {
  const [loading, setLoading] = useState(true);
  const [allPosts, setAllPosts] = useState(null);
  return (
    <main>
      <section>
        <div>
          <h1>The Community Showcase</h1>
          <p>
            Browse through a collection of imaginative and visually stunning
            images generated by DALL·E AI
          </p>
        </div>

        <div className={styles.form}>
          <FormField />
        </div>

        <div className={styles.aaa}>
          {loading ? (
            <div className={styles.bbb}>
              <Loader className={styles.loader} />
            </div>
          ) : (
            <></>
          )}
        </div>
      </section>
    </main>
  );
}

export default Home;
